name: gestures
description: A video dictionary for sign language.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: "1.1.0"
environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: "^3.29.3"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  chewie: ^1.11.3
  collection: ^1.19.1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  go_router: ^15.1.2
  http: ^1.4.0
  micha_core: ^1.1.0
  package_info_plus: ^8.3.0
  universal_html: ^2.2.4
  video_player: ^2.9.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^2.9.0
  build_runner: ^2.4.15
  build_verify: ^3.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/fira_sans/
  # prevent fallback font from being downloaded from google fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
