name: gestures
description: A video dictionary for sign language.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.5
environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: "^3.16.9"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  chewie: ^1.7.4
  collection: ^1.18.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  go_router: ^13.1.0
  http: ^1.2.0
  micha_core: ^0.5.2
  package_info_plus: ^5.0.1
  universal_html: ^2.2.4
  video_player: ^2.8.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  go_router_builder: ^2.4.1
  build_runner: ^2.4.8
  build_verify: ^3.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/fira_sans/
  # prevent fallback font from being downloaded from google fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
